# permissions for end users to edit placementrules.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: placementrule-editor-role
rules:
- apiGroups:
  - apps.open-cluster-management.io
  resources:
  - placementrules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.open-cluster-management.io
  resources:
  - placementrules/status
  verbs:
  - get
